/**
 * Dataset immobili Milano — Dati di esempio
 * In produzione questi dati verrebbero popolati da:
 * - Catasto (Agenzia delle Entrate / Sister)
 * - Conservatoria (visure ipotecarie)
 * - Tribunale di Milano (aste/fallimenti)
 * - Anagrafe comunale (dati demografici proprietari)
 * - Osservatorio Immobiliare (valori di mercato)
 */

const MILAN_PROPERTIES = [
    // === ZONA NORD ===
    {
        id: 1,
        indirizzo: "Via Farini 28",
        cap: "20159",
        zona: "nord",
        quartiere: "Isola/Garibaldi",
        tipologia: "uffici",
        superficie: 320,
        piani: "2°-3°",
        annoCostruzione: 1962,
        lat: 45.4870,
        lng: 9.1865,
        proprietario: "Immobiliare Farini Srl (in liquidazione)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 28,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 4,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 580000,
        note: "Società in liquidazione dal 2023. Uffici vuoti dal 2022. Zona in forte rivalutazione per progetto Porta Nuova."
    },
    {
        id: 2,
        indirizzo: "Viale Stelvio 66",
        cap: "20159",
        zona: "nord",
        quartiere: "Dergano",
        tipologia: "capannoni",
        superficie: 850,
        piani: "T",
        annoCostruzione: 1955,
        lat: 45.4985,
        lng: 9.1752,
        proprietario: "Eredi Colombo Giovanni",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "semiabbandonato",
        anniUltimaRistrutturazione: 42,
        successioneRecente: true,
        anniDaSuccessione: 1,
        fallimento: false,
        asta: false,
        anniFermo: 8,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 1200000,
        note: "Successione aperta nel 2025. Ex officina meccanica. 3 eredi, nessuno interessato a proseguire attività. Zona in trasformazione."
    },
    {
        id: 3,
        indirizzo: "Via Bovisa 15",
        cap: "20151",
        zona: "nord",
        quartiere: "Bovisa",
        tipologia: "terreni",
        superficie: 2200,
        piani: "-",
        annoCostruzione: null,
        lat: 45.5045,
        lng: 9.1580,
        proprietario: "Rossi Maria",
        etaProprietario: 88,
        tipoProprietario: "persona_fisica",
        statoImmobile: "abbandonato",
        anniUltimaRistrutturazione: null,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 15,
        erediNoti: false,
        inVendita: false,
        valoreStimato: 1800000,
        note: "Terreno industriale dismesso. Proprietaria molto anziana, vedova, senza eredi diretti. Zona Bovisa in forte sviluppo (Politecnico)."
    },
    {
        id: 4,
        indirizzo: "Via Imbonati 52",
        cap: "20159",
        zona: "nord",
        quartiere: "Dergano",
        tipologia: "garage",
        superficie: 180,
        piani: "S1",
        annoCostruzione: 1968,
        lat: 45.4952,
        lng: 9.1710,
        proprietario: "Bianchi Franco",
        etaProprietario: 82,
        tipoProprietario: "persona_fisica",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 35,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 6,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 145000,
        note: "Autorimessa con 12 posti auto. In disuso da anni, proprietario anziano ricoverato in RSA."
    },
    {
        id: 5,
        indirizzo: "Via Valtellina 12",
        cap: "20159",
        zona: "isola",
        quartiere: "Isola",
        tipologia: "uffici",
        superficie: 450,
        piani: "1°-2°",
        annoCostruzione: 1958,
        lat: 45.4892,
        lng: 9.1830,
        proprietario: "Eredi Martini",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 22,
        successioneRecente: true,
        anniDaSuccessione: 2,
        fallimento: false,
        asta: false,
        anniFermo: 3,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 890000,
        note: "Ex studio professionale. Successione 2024, 4 eredi in disaccordo sulla destinazione. Zona premium Isola."
    },

    // === ZONA SUD ===
    {
        id: 6,
        indirizzo: "Viale Ortles 80",
        cap: "20139",
        zona: "sud",
        quartiere: "Corvetto",
        tipologia: "uffici",
        superficie: 1200,
        piani: "T-3°",
        annoCostruzione: 1970,
        lat: 45.4380,
        lng: 9.2220,
        proprietario: "Progetto Domus Flora (Studio Contrino & Bottinelli)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 18,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 0,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 2400000,
        note: "⭐ PROGETTO IN CORSO — Domus Flora. Operazione Studio Contrino & Bottinelli."
    },
    {
        id: 7,
        indirizzo: "Via Ripamonti 150",
        cap: "20141",
        zona: "sud",
        quartiere: "Vigentino",
        tipologia: "capannoni",
        superficie: 1500,
        piani: "T",
        annoCostruzione: 1952,
        lat: 45.4350,
        lng: 9.2050,
        proprietario: "Meccanica Lombarda Spa (fallita)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "abbandonato",
        anniUltimaRistrutturazione: 45,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: true,
        anniFermo: 7,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 1900000,
        note: "Capannone industriale all'asta. Fallimento 2023. Base asta €1.2M. Buon potenziale per riconversione residenziale."
    },
    {
        id: 8,
        indirizzo: "Via dei Missaglia 97",
        cap: "20142",
        zona: "sud",
        quartiere: "Gratosoglio",
        tipologia: "terreni",
        superficie: 3500,
        piani: "-",
        annoCostruzione: null,
        lat: 45.4180,
        lng: 9.1680,
        proprietario: "Ferrario Giuseppe",
        etaProprietario: 91,
        tipoProprietario: "persona_fisica",
        statoImmobile: "abbandonato",
        anniUltimaRistrutturazione: null,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 20,
        erediNoti: false,
        inVendita: false,
        valoreStimato: 2100000,
        note: "Terreno industriale dismesso da 20 anni. Proprietario 91enne, vedovo, senza eredi. Potenziale enorme per sviluppo."
    },
    {
        id: 9,
        indirizzo: "Via Quaranta 36",
        cap: "20139",
        zona: "sud",
        quartiere: "Corvetto",
        tipologia: "garage",
        superficie: 250,
        piani: "S1-S2",
        annoCostruzione: 1972,
        lat: 45.4420,
        lng: 9.2180,
        proprietario: "Eredi Longoni",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 30,
        successioneRecente: true,
        anniDaSuccessione: 1,
        fallimento: false,
        asta: false,
        anniFermo: 2,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 320000,
        note: "Autorimessa 18 box. Successione recente, eredi in fase di valutazione vendita."
    },
    {
        id: 10,
        indirizzo: "Via Bonfadini 60",
        cap: "20139",
        zona: "sud",
        quartiere: "Rogoredo",
        tipologia: "capannoni",
        superficie: 2000,
        piani: "T-1°",
        annoCostruzione: 1965,
        lat: 45.4310,
        lng: 9.2350,
        proprietario: "Tessile Sud Milano Srl (cessata)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "semiabbandonato",
        anniUltimaRistrutturazione: 38,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 6,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 2800000,
        note: "Ex fabbrica tessile. Società cessata. Area Rogoredo-Santa Giulia in forte sviluppo. Ideale per riconversione."
    },

    // === ZONA EST ===
    {
        id: 11,
        indirizzo: "Via Mecenate 76",
        cap: "20138",
        zona: "est",
        quartiere: "Forlanini",
        tipologia: "uffici",
        superficie: 600,
        piani: "T-2°",
        annoCostruzione: 1975,
        lat: 45.4530,
        lng: 9.2440,
        proprietario: "Moretti Costruzioni Srl (in liquidazione)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 20,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 3,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 750000,
        note: "Uffici direzionali vuoti. Società in liquidazione. Zona ben collegata (Linate)."
    },
    {
        id: 12,
        indirizzo: "Via Salomone 41",
        cap: "20138",
        zona: "est",
        quartiere: "Lambrate",
        tipologia: "terreni",
        superficie: 1800,
        piani: "-",
        annoCostruzione: null,
        lat: 45.4620,
        lng: 9.2380,
        proprietario: "Cattaneo Aldo",
        etaProprietario: 84,
        tipoProprietario: "persona_fisica",
        statoImmobile: "abbandonato",
        anniUltimaRistrutturazione: null,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 12,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 1400000,
        note: "Terreno ex attività produttiva. Proprietario anziano, figli non interessati. Lambrate zona in trasformazione."
    },
    {
        id: 13,
        indirizzo: "Via Padova 276",
        cap: "20132",
        zona: "est",
        quartiere: "Crescenzago",
        tipologia: "negozi",
        superficie: 380,
        piani: "T-1°",
        annoCostruzione: 1960,
        lat: 45.4880,
        lng: 9.2350,
        proprietario: "Eredi Brambilla Luigi",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "pessimo",
        anniUltimaRistrutturazione: 35,
        successioneRecente: true,
        anniDaSuccessione: 2,
        fallimento: false,
        asta: false,
        anniFermo: 5,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 420000,
        note: "Negozio con magazzino. Successione 2024. Immobile in pessimo stato, eredi valutano dismissione."
    },
    {
        id: 14,
        indirizzo: "Via Rubattino 84",
        cap: "20134",
        zona: "est",
        quartiere: "Lambrate",
        tipologia: "capannoni",
        superficie: 3200,
        piani: "T",
        annoCostruzione: 1948,
        lat: 45.4685,
        lng: 9.2410,
        proprietario: "Fonderia Lombarda Spa (cessata)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "abbandonato",
        anniUltimaRistrutturazione: 50,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: true,
        anniFermo: 10,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 4500000,
        note: "Grande area industriale dismessa. All'asta dal tribunale. Area Rubattino in forte sviluppo urbanistico."
    },

    // === ZONA OVEST ===
    {
        id: 15,
        indirizzo: "Via Lorenteggio 257",
        cap: "20152",
        zona: "ovest",
        quartiere: "Lorenteggio",
        tipologia: "uffici",
        superficie: 420,
        piani: "1°-3°",
        annoCostruzione: 1968,
        lat: 45.4480,
        lng: 9.1350,
        proprietario: "Verdi Anna Maria",
        etaProprietario: 79,
        tipoProprietario: "persona_fisica",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 25,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 7,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 520000,
        note: "Uffici vuoti da 7 anni. Proprietaria anziana, figli emigrati. Zona in rivalutazione per M4."
    },
    {
        id: 16,
        indirizzo: "Via Bisceglie 80",
        cap: "20152",
        zona: "ovest",
        quartiere: "Bande Nere",
        tipologia: "garage",
        superficie: 350,
        piani: "S1-S2",
        annoCostruzione: 1970,
        lat: 45.4430,
        lng: 9.1280,
        proprietario: "Eredi Colombo",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 32,
        successioneRecente: true,
        anniDaSuccessione: 3,
        fallimento: false,
        asta: false,
        anniFermo: 4,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 420000,
        note: "Autorimessa 25 box. Successione 2023, eredi indecisi. Buon rendimento potenziale."
    },
    {
        id: 17,
        indirizzo: "Via Novara 350",
        cap: "20153",
        zona: "ovest",
        quartiere: "San Siro",
        tipologia: "terreni",
        superficie: 4500,
        piani: "-",
        annoCostruzione: null,
        lat: 45.4720,
        lng: 9.1150,
        proprietario: "Immobiliare San Siro Srl",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "abbandonato",
        anniUltimaRistrutturazione: null,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: true,
        anniFermo: 8,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 6500000,
        note: "Grande terreno edificabile. All'asta per fallimento. Zona San Siro con progetto nuovo stadio. Opportunità top."
    },
    {
        id: 18,
        indirizzo: "Via Washington 70",
        cap: "20146",
        zona: "ovest",
        quartiere: "Washington",
        tipologia: "uffici",
        superficie: 280,
        piani: "3°-4°",
        annoCostruzione: 1958,
        lat: 45.4620,
        lng: 9.1510,
        proprietario: "De Luca Roberto",
        etaProprietario: 86,
        tipoProprietario: "persona_fisica",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 30,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 5,
        erediNoti: false,
        inVendita: false,
        valoreStimato: 680000,
        note: "Ex studio notarile. Proprietario 86enne, vedovo, senza eredi diretti. Zona pregiata."
    },

    // === ZONA CENTRO ===
    {
        id: 19,
        indirizzo: "Via Palladio 18",
        cap: "20135",
        zona: "centro",
        quartiere: "Porta Romana",
        tipologia: "uffici",
        superficie: 800,
        piani: "T-4°",
        annoCostruzione: 1965,
        lat: 45.4530,
        lng: 9.2000,
        proprietario: "Verde Palladio (Studio Contrino & Bottinelli)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "buono",
        anniUltimaRistrutturazione: 2,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 0,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 3200000,
        note: "⭐ PROGETTO COMPLETATO — Verde Palladio. Operazione di successo Studio Contrino & Bottinelli."
    },
    {
        id: 20,
        indirizzo: "Corso di Porta Ticinese 85",
        cap: "20123",
        zona: "navigli",
        quartiere: "Navigli",
        tipologia: "negozi",
        superficie: 200,
        piani: "T",
        annoCostruzione: 1935,
        lat: 45.4530,
        lng: 9.1780,
        proprietario: "Galli Pietro",
        etaProprietario: 92,
        tipoProprietario: "persona_fisica",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 40,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 3,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 950000,
        note: "Negozio storico chiuso. Proprietario 92enne. Posizione premium sui Navigli. Alto potenziale."
    },
    {
        id: 21,
        indirizzo: "Via Torino 30",
        cap: "20123",
        zona: "centro",
        quartiere: "Centro Storico",
        tipologia: "uffici",
        superficie: 550,
        piani: "2°-4°",
        annoCostruzione: 1920,
        lat: 45.4610,
        lng: 9.1840,
        proprietario: "Eredi Fontana",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 35,
        successioneRecente: true,
        anniDaSuccessione: 1,
        fallimento: false,
        asta: false,
        anniFermo: 2,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 2800000,
        note: "Palazzo storico, uffici ai piani alti. Successione recente 2025, 5 eredi. Posizione centralissima."
    },
    {
        id: 22,
        indirizzo: "Via Manzoni 12",
        cap: "20121",
        zona: "centro",
        quartiere: "Quadrilatero",
        tipologia: "uffici",
        superficie: 380,
        piani: "3°-4°",
        annoCostruzione: 1910,
        lat: 45.4700,
        lng: 9.1920,
        proprietario: "Fondazione Manzoni (in scioglimento)",
        etaProprietario: null,
        tipoProprietario: "ente",
        statoImmobile: "discreto",
        anniUltimaRistrutturazione: 15,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 2,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 3500000,
        note: "Ente in scioglimento, patrimonio immobiliare da liquidare. Posizione ultra-premium."
    },

    // === ZONA NAVIGLI ===
    {
        id: 23,
        indirizzo: "Alzaia Naviglio Grande 44",
        cap: "20144",
        zona: "navigli",
        quartiere: "Navigli",
        tipologia: "negozi",
        superficie: 160,
        piani: "T",
        annoCostruzione: 1940,
        lat: 45.4500,
        lng: 9.1680,
        proprietario: "Rizzo Antonia",
        etaProprietario: 87,
        tipoProprietario: "persona_fisica",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 28,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 4,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 720000,
        note: "Ex bottega artigiana. Proprietaria anziana. Fronte Naviglio, altissimo potenziale commerciale."
    },
    {
        id: 24,
        indirizzo: "Via Vigevano 18",
        cap: "20144",
        zona: "navigli",
        quartiere: "Navigli",
        tipologia: "garage",
        superficie: 120,
        piani: "S1",
        annoCostruzione: 1965,
        lat: 45.4520,
        lng: 9.1720,
        proprietario: "Eredi Sala",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "pessimo",
        anniUltimaRistrutturazione: 40,
        successioneRecente: true,
        anniDaSuccessione: 1,
        fallimento: false,
        asta: false,
        anniFermo: 3,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 180000,
        note: "Garage/deposito in pessimo stato. Successione 2025. Zona Navigli molto richiesta."
    },

    // === LAMBRATE / CITTA STUDI ===
    {
        id: 25,
        indirizzo: "Via Conte Rosso 20",
        cap: "20134",
        zona: "lambrate",
        quartiere: "Lambrate",
        tipologia: "capannoni",
        superficie: 1100,
        piani: "T",
        annoCostruzione: 1950,
        lat: 45.4750,
        lng: 9.2280,
        proprietario: "Tipografia Ambrosiana Srl (cessata)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "semiabbandonato",
        anniUltimaRistrutturazione: 40,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 5,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 1650000,
        note: "Ex tipografia industriale. Società cessata. Lambrate è il nuovo quartiere creativo di Milano."
    },
    {
        id: 26,
        indirizzo: "Via Pitteri 58",
        cap: "20134",
        zona: "lambrate",
        quartiere: "Lambrate",
        tipologia: "uffici",
        superficie: 350,
        piani: "1°-2°",
        annoCostruzione: 1972,
        lat: 45.4780,
        lng: 9.2320,
        proprietario: "Mazza Giovanni",
        etaProprietario: 81,
        tipoProprietario: "persona_fisica",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 22,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 4,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 480000,
        note: "Uffici vuoti. Proprietario anziano con problemi di salute. Eredi non interessati."
    },

    // === BOVISA / DERGANO ===
    {
        id: 27,
        indirizzo: "Via Baldinucci 28",
        cap: "20158",
        zona: "bovisa",
        quartiere: "Dergano",
        tipologia: "negozi",
        superficie: 140,
        piani: "T",
        annoCostruzione: 1955,
        lat: 45.4970,
        lng: 9.1790,
        proprietario: "Barbieri Elena",
        etaProprietario: 85,
        tipoProprietario: "persona_fisica",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 30,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 8,
        erediNoti: false,
        inVendita: false,
        valoreStimato: 280000,
        note: "Ex merceria chiusa da 8 anni. Proprietaria anziana senza eredi. Zona Dergano in forte gentrificazione."
    },
    {
        id: 28,
        indirizzo: "Via Cosimo del Fante 16",
        cap: "20122",
        zona: "centro",
        quartiere: "Porta Romana",
        tipologia: "garage",
        superficie: 500,
        piani: "S1-S3",
        annoCostruzione: 1960,
        lat: 45.4555,
        lng: 9.1950,
        proprietario: "Parcheggi Centro Srl (in concordato)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 25,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 2,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 1100000,
        note: "Autorimessa sotterranea 40 posti. Società in concordato preventivo. Centro Milano, altissima domanda parcheggi."
    },
    {
        id: 29,
        indirizzo: "Via Tertulliano 70",
        cap: "20137",
        zona: "sud",
        quartiere: "Porta Romana",
        tipologia: "capannoni",
        superficie: 900,
        piani: "T",
        annoCostruzione: 1958,
        lat: 45.4480,
        lng: 9.2100,
        proprietario: "Eredi Rizzi Carlo",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "semiabbandonato",
        anniUltimaRistrutturazione: 38,
        successioneRecente: true,
        anniDaSuccessione: 2,
        fallimento: false,
        asta: false,
        anniFermo: 6,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 1350000,
        note: "Capannone ex falegnameria. Successione 2024. Zona Fondazione Prada, in forte rivalutazione."
    },
    {
        id: 30,
        indirizzo: "Corso Lodi 47",
        cap: "20139",
        zona: "sud",
        quartiere: "Lodi/Corvetto",
        tipologia: "uffici",
        superficie: 290,
        piani: "2°-3°",
        annoCostruzione: 1966,
        lat: 45.4450,
        lng: 9.2130,
        proprietario: "Neri Graziella",
        etaProprietario: 78,
        tipoProprietario: "persona_fisica",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 28,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 5,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 390000,
        note: "Uffici in disuso. Proprietaria anziana, figli lontani. Zona Corso Lodi in miglioramento."
    },
    {
        id: 31,
        indirizzo: "Via Giambellino 120",
        cap: "20146",
        zona: "ovest",
        quartiere: "Giambellino",
        tipologia: "negozi",
        superficie: 220,
        piani: "T",
        annoCostruzione: 1955,
        lat: 45.4460,
        lng: 9.1430,
        proprietario: "Eredi Costa Michele",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "pessimo",
        anniUltimaRistrutturazione: 42,
        successioneRecente: true,
        anniDaSuccessione: 1,
        fallimento: false,
        asta: false,
        anniFermo: 10,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 230000,
        note: "Ex officina auto. Chiusa da 10 anni. Successione 2025, eredi vogliono liquidare. Zona in rigenerazione."
    },
    {
        id: 32,
        indirizzo: "Viale Monza 140",
        cap: "20127",
        zona: "est",
        quartiere: "Gorla",
        tipologia: "uffici",
        superficie: 480,
        piani: "T-2°",
        annoCostruzione: 1970,
        lat: 45.4920,
        lng: 9.2200,
        proprietario: "Consulting Nord Srl (cessata)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 18,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 3,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 620000,
        note: "Uffici direzionali. Società cessata nel 2023. Viale Monza, buona visibilità e collegamenti."
    },
    {
        id: 33,
        indirizzo: "Via Sammartini 15",
        cap: "20125",
        zona: "isola",
        quartiere: "Stazione Centrale",
        tipologia: "garage",
        superficie: 800,
        piani: "S1-S3",
        annoCostruzione: 1958,
        lat: 45.4850,
        lng: 9.2020,
        proprietario: "Garage Centrale Spa (in concordato)",
        etaProprietario: null,
        tipoProprietario: "società",
        statoImmobile: "mediocre",
        anniUltimaRistrutturazione: 20,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: true,
        asta: false,
        anniFermo: 1,
        erediNoti: null,
        inVendita: false,
        valoreStimato: 2200000,
        note: "Grande autorimessa vicino Stazione Centrale. Concordato preventivo. Enorme potenziale per posizione."
    },
    {
        id: 34,
        indirizzo: "Via Porpora 150",
        cap: "20131",
        zona: "lambrate",
        quartiere: "Città Studi",
        tipologia: "uffici",
        superficie: 300,
        piani: "1°-2°",
        annoCostruzione: 1964,
        lat: 45.4780,
        lng: 9.2170,
        proprietario: "Pozzi Alberto",
        etaProprietario: 90,
        tipoProprietario: "persona_fisica",
        statoImmobile: "da_ristrutturare",
        anniUltimaRistrutturazione: 32,
        successioneRecente: false,
        anniDaSuccessione: null,
        fallimento: false,
        asta: false,
        anniFermo: 8,
        erediNoti: false,
        inVendita: false,
        valoreStimato: 490000,
        note: "Ex studio medico. Proprietario 90enne, nessun erede noto. Zona Città Studi molto richiesta."
    },
    {
        id: 35,
        indirizzo: "Via Savona 97",
        cap: "20144",
        zona: "navigli",
        quartiere: "Tortona",
        tipologia: "capannoni",
        superficie: 700,
        piani: "T",
        annoCostruzione: 1945,
        lat: 45.4520,
        lng: 9.1600,
        proprietario: "Eredi Pellegrini",
        etaProprietario: null,
        tipoProprietario: "eredi",
        statoImmobile: "semiabbandonato",
        anniUltimaRistrutturazione: 35,
        successioneRecente: true,
        anniDaSuccessione: 2,
        fallimento: false,
        asta: false,
        anniFermo: 4,
        erediNoti: true,
        inVendita: false,
        valoreStimato: 2100000,
        note: "Capannone zona Tortona/design district. Successione 2024. Valore altissimo per la posizione."
    }
];
